In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%pip install seaborn
import seaborn as sns
%pip install openpyxl

In [5]:
data = pd.read_csv("car_age_price.csv")

In [6]:
data.head()

   Year   Price
0  2018  465000
1  2019  755000
2  2019  700000
3  2018  465000
4  2018  465000

In [7]:
data.shape

(112, 2)

In [8]:
data.isna().sum()

Year     0
Price    0
dtype: int64

In [9]:
data.columns

Index(['Year', 'Price'], dtype='str')

In [10]:
x = data[['Year']]
y = data['Price']

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2,
random_state = 42)

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
lin_reg = LinearRegression()

In [22]:
model = lin_reg.fit(x_train,y_train)

In [23]:
predictions = model.predict(x_test)

In [24]:
x_test

     Year
40   2019
65   2017
4    2018
47   2018
42   2018
69   2015
26   2017
11   2018
10   2019
44   2019
73   2013
55   2017
68   2015
97   2020
0    2018
18   2019
53   2013
80   2015
103  2017
91   2017
36   2017
12   2017
31   2017

In [25]:
predictions

array([600775.91252081, 505558.77690466, 553167.34471273, 553167.34471273,
       553167.34471273, 410341.6412885 , 505558.77690466, 553167.34471273,
       600775.91252081, 600775.91252081, 315124.50567235, 505558.77690466,
       410341.6412885 , 648384.48032889, 553167.34471273, 600775.91252081,
       315124.50567235, 410341.6412885 , 505558.77690466, 505558.77690466,
       505558.77690466, 505558.77690466, 505558.77690466])

In [26]:
y_test

40     525000
65     495000
4      465000
47     450000
42     550000
69     300000
26     550000
11     500000
10     500000
44     550000
73     320000
55     550000
68     465000
97     640000
0      465000
18     500000
53     345000
80     390000
103    375000
91     520000
36     550000
12     500000
31     550000
Name: Price, dtype: int64

In [27]:
from sklearn.metrics import mean_squared_error, r2_score

In [28]:
print('Mean Squared Error = ', mean_squared_error(y_test, predictions))
print('R Squared Value = ', r2_score(y_test, predictions))

Mean Squared Error =  4326906256.829671
R Squared Value =  0.36759313425902185

### price of a 2022 model

In [31]:
prediction = model.predict(pd.DataFrame({'Year': [2022]}))

[743601.61594504]

In [32]:
print(prediction)

[743601.61594504]

### Lasso Regression

In [34]:
from sklearn.linear_model import Lasso

In [35]:
lasso_model = Lasso(alpha = 0.1)
lasso_model = lasso_model.fit(x_train, y_train)

In [36]:
predictions_lasso = lasso_model.predict(x_test)

In [37]:
print('Mean Squared Error = ', mean_squared_error(y_test, predictions_lasso))
print('R Squared Value = ', r2_score(y_test, predictions_lasso))

Mean Squared Error =  4326901608.19506
R Squared Value =  0.36759381368868127